wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.11
    start_time: 1650105782
    t:
      1:
      - 1
      - 3
      - 41
      2:
      - 1
      - 3
      - 41
      3:
      - 13
      - 16
      - 19
      4: 3.8.11
      5: 0.12.11
      8:
      - 4
      - 5
adam:
  desc: null
  value: false
artifact_alias:
  desc: null
  value: latest
batch_size:
  desc: null
  value: 2
bbox_interval:
  desc: null
  value: -1
bucket:
  desc: null
  value: ''
cache_images:
  desc: null
  value: false
cfg:
  desc: null
  value: models/yolov5m.yaml
data:
  desc: null
  value: data/voc.yaml
data_dict:
  desc: null
  value:
    download: bash data/scripts/get_voc.sh
    names:
    - Sharp
    - Flat
    - Natural
    - Gclef
    - Fclef
    - Cclef
    - TimeSig
    - Rests1
    - Rests2
    - Rests4
    - Rests8
    - Rests16
    - Rests32
    - Rests64
    - Rests128
    - Bass
    - Guit
    - Tpt
    - Hn
    - Tbn
    - Fl
    - Ob
    - Cl
    - Bsn
    - Vln
    - Vla
    - Vlc
    - Pno
    - Wh
    - m
    - Trb
    - p
    - f
    - Sax
    - Hrp
    - Cb
    - 1_-5
    - 1_-4
    - 1_-3
    - 1_-2
    - 1_-1
    - '1_0'
    - '1_1'
    - '1_2'
    - '1_3'
    - '1_4'
    - '1_5'
    - '1_6'
    - '1_7'
    - '1_8'
    - '1_9'
    - '1_10'
    - '1_11'
    - '1_12'
    - '1_13'
    - '1_14'
    - '1_15'
    - 2_-6
    - 2_-5
    - 2_-4
    - 2_-3
    - 2_-2
    - 2_-1
    - '2_0'
    - '2_1'
    - '2_2'
    - '2_3'
    - '2_4'
    - '2_5'
    - '2_6'
    - '2_7'
    - '2_8'
    - '2_9'
    - '2_10'
    - '2_11'
    - '2_12'
    - '2_13'
    - '2_14'
    - '2_15'
    - 4_-6
    - 4_-5
    - 4_-4
    - 4_-3
    - 4_-2
    - 4_-1
    - '4_0'
    - '4_1'
    - '4_2'
    - '4_3'
    - '4_4'
    - '4_5'
    - '4_6'
    - '4_7'
    - '4_8'
    - '4_9'
    - '4_10'
    - '4_11'
    - '4_12'
    - '4_13'
    - '4_14'
    - '4_15'
    - 8_-7
    - 8_-6
    - 8_-5
    - 8_-4
    - 8_-3
    - 8_-2
    - 8_-1
    - '8_0'
    - '8_1'
    - '8_2'
    - '8_3'
    - '8_4'
    - '8_5'
    - '8_6'
    - '8_7'
    - '8_8'
    - '8_9'
    - '8_10'
    - '8_11'
    - '8_12'
    - '8_13'
    - '8_14'
    - '8_15'
    - '8_16'
    - '8_17'
    - 16_-8
    - 16_-7
    - 16_-6
    - 16_-5
    - 16_-4
    - 16_-3
    - 16_-2
    - 16_-1
    - '16_0'
    - '16_1'
    - '16_2'
    - '16_3'
    - '16_4'
    - '16_5'
    - '16_6'
    - '16_7'
    - '16_8'
    - '16_9'
    - '16_10'
    - '16_11'
    - '16_12'
    - '16_13'
    - '16_14'
    - '16_15'
    - '16_16'
    - '16_17'
    - '16_18'
    - 32_-2
    - 32_-1
    - '32_0'
    - '32_1'
    - '32_2'
    - '32_3'
    - '32_4'
    - '32_5'
    - '32_6'
    - '32_7'
    - '32_8'
    - '32_9'
    - '32_10'
    - '32_11'
    - '32_12'
    - '32_13'
    - '32_14'
    - '32_15'
    - 64_-5
    - 64_-4
    - 64_-3
    - 64_-2
    - 64_-1
    - '64_0'
    - '64_1'
    - '64_2'
    - '64_3'
    - '64_4'
    - '64_5'
    - '64_6'
    - '64_7'
    - '64_8'
    - '64_9'
    - '64_10'
    - '64_11'
    - '64_12'
    - '64_13'
    - '64_14'
    - '64_15'
    nc: 192
    train: VOCdevkit/images/train/
    val: VOCdevkit/images/val/
device:
  desc: null
  value: ''
entity:
  desc: null
  value: null
epochs:
  desc: null
  value: 1
evolve:
  desc: null
  value: false
exist_ok:
  desc: null
  value: false
global_rank:
  desc: null
  value: -1
hyp:
  desc: null
  value:
    anchor_t: 4.0
    box: 0.05
    cls: 0.5
    cls_pw: 1.0
    degrees: 0.0
    fl_gamma: 0.0
    fliplr: 0.5
    flipud: 0.0
    hsv_h: 0.015
    hsv_s: 0.7
    hsv_v: 0.4
    iou_t: 0.2
    lr0: 0.01
    lrf: 0.2
    mixup: 0.0
    momentum: 0.937
    mosaic: 1.0
    obj: 1.0
    obj_pw: 1.0
    perspective: 0.0
    scale: 0.5
    shear: 0.0
    translate: 0.1
    warmup_bias_lr: 0.1
    warmup_epochs: 3.0
    warmup_momentum: 0.8
    weight_decay: 0.0005
image_weights:
  desc: null
  value: false
img_size:
  desc: null
  value:
  - 640
  - 640
label_smoothing:
  desc: null
  value: 0.0
linear_lr:
  desc: null
  value: false
local_rank:
  desc: null
  value: -1
multi_scale:
  desc: null
  value: false
name:
  desc: null
  value: exp
noautoanchor:
  desc: null
  value: false
nosave:
  desc: null
  value: false
notest:
  desc: null
  value: false
opt:
  desc: null
  value:
    adam: false
    artifact_alias: latest
    batch_size: 2
    bbox_interval: -1
    bucket: ''
    cache_images: false
    cfg: models/yolov5m.yaml
    data: data/voc.yaml
    device: ''
    entity: null
    epochs: 1
    evolve: false
    exist_ok: false
    global_rank: -1
    hyp:
      anchor_t: 4.0
      box: 0.05
      cls: 0.5
      cls_pw: 1.0
      degrees: 0.0
      fl_gamma: 0.0
      fliplr: 0.5
      flipud: 0.0
      hsv_h: 0.015
      hsv_s: 0.7
      hsv_v: 0.4
      iou_t: 0.2
      lr0: 0.01
      lrf: 0.2
      mixup: 0.0
      momentum: 0.937
      mosaic: 1.0
      obj: 1.0
      obj_pw: 1.0
      perspective: 0.0
      scale: 0.5
      shear: 0.0
      translate: 0.1
      warmup_bias_lr: 0.1
      warmup_epochs: 3.0
      warmup_momentum: 0.8
      weight_decay: 0.0005
    image_weights: false
    img_size:
    - 640
    - 640
    label_smoothing: 0.0
    linear_lr: false
    local_rank: -1
    multi_scale: false
    name: exp
    noautoanchor: false
    nosave: false
    notest: false
    project: runs/train
    quad: false
    rect: false
    resume: false
    save_dir: runs/train/exp
    save_period: -1
    single_cls: false
    sync_bn: false
    total_batch_size: 2
    upload_dataset: false
    weights: weights/yolov5m.pt
    workers: 8
    world_size: 1
project:
  desc: null
  value: runs/train
quad:
  desc: null
  value: false
rect:
  desc: null
  value: false
resume:
  desc: null
  value: false
save_dir:
  desc: null
  value: runs/train/exp
save_period:
  desc: null
  value: -1
single_cls:
  desc: null
  value: false
sync_bn:
  desc: null
  value: false
total_batch_size:
  desc: null
  value: 2
upload_dataset:
  desc: null
  value: false
weights:
  desc: null
  value: weights/yolov5m.pt
workers:
  desc: null
  value: 8
world_size:
  desc: null
  value: 1
